#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${PYTHON_BIN:-python3}"

log() {
  printf '\n[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
}

run_step() {
  local step_name="$1"
  local cmd="$2"
  log "$step_name"
  eval "$cmd"
}

mkdir -p raw_pdb clean_pdb metadata analysis rfdiffusion3_inputs rfdiffusion3_inputs/plans rfdiffusion3_inputs/design_specs rfdiffusion3_inputs/unified_templates

if [ ! -f "raw_pdb/.download_complete" ]; then
  log "Downloading and organizing PDBs"
  "$PYTHON_BIN" download_and_organize_pdbs.py
  touch raw_pdb/.download_complete
fi

run_step "Analyzing structures" "$PYTHON_BIN analyze_pdbs.py"
run_step "Preparing RFdiffusion3 inputs" "$PYTHON_BIN prepare_rfdiffusion3_inputs.py"
run_step "Building residue-level plans" "$PYTHON_BIN make_rfdiffusion3_residue_plans.py"
run_step "Generating RFdiffusion3 design JSONs" "$PYTHON_BIN generate_rfdiffusion3_design_inputs.py"
run_step "Generating unified templates" "$PYTHON_BIN make_rfdiffusion3_unified_template.py"

cat > rfdiffusion3_inputs/README.txt <<'EOF'
Generated by run_pipeline.sh.

Folders:
- single_chain/: primary chain selections for each target
- backbone_only/: backbone-only inputs for constrained runs
- metadata/: per-target metadata JSON
- plans/: residue-level fixed/diffuse plans
- design_specs/: final RFdiffusion3 JSON inputs for `rfd3 design`
- unified_templates/: unified templates for batch experimental runs
- registry.json: master index of prepared targets
EOF

log "Pipeline complete"
log "Next files to inspect: rfdiffusion3_inputs/unified_templates/*.json"
