#!/usr/bin/env bash
# One-click replacement-NMF sweep: one linear layer per job, trained on PDB.
#
# Each job exact-matches a single 2D Linear and replaces only that layer
# (nmf.match_mode=exact, nmf.max_replacements=1). Parent modules such as
# Transition are never replaced as a group.
#
# LAYER_SET:
#   encoder  input-shaping linears (default)
#   proj     token/atom projection linears
#   head     output-head linears
#   all      union of the three families
#   one      a single LAYER=module.path job
#
# Optional:
#   INCLUDE_BASELINE=1  also run a no-NMF PDB baseline
#   PRESET=a6000        GPU-appropriate training sizes (see "GPU sizing" below)
#
# Wall-clock: the sweep is a plain sequential loop of jobs on ONE GPU. With
# spare cards, split the families and share a single sweep directory so every
# result still lands in one report:
#   D=/backup01/zzj/logs/train_nmf_zkp_pdb/sweep_shared
#   GPU=2 SWEEP_DIR=$D INCLUDE_BASELINE=1 LAYER_SET=proj    bash .../run_nmf_zkp_pdb_sweep.sh &
#   GPU=4 SWEEP_DIR=$D INCLUDE_BASELINE=0 LAYER_SET=encoder bash .../run_nmf_zkp_pdb_sweep.sh &
#   GPU=5 SWEEP_DIR=$D INCLUDE_BASELINE=0 LAYER_SET=head    bash .../run_nmf_zkp_pdb_sweep.sh &
#   wait
#   python models/rfd3/scripts/summarize_nmf_zkp_pdb_sweep.py $D --seed 42
#   python models/rfd3/scripts/plot_nmf_zkp_pdb_metrics.py $D --ckpt <ckpt>
# Run the baseline in exactly ONE invocation. Each invocation rewrites
# comparison_table.md from the exit codes present at that moment, so once all
# jobs finish treat paper_summary.* / paper_metrics.* (regenerated by the two
# commands above) as the authoritative report. Keep the total number of
# dataloader workers across the concurrent jobs <= available CPU cores.
#
# Ran out of time before the loop finished? Everything below (comparison_table,
# paper_summary, figures, paper_training_cost) is written ONLY after the last
# job returns, so a killed run leaves none of them. Per-job artefacts are still
# on disk, so build the report from those instead:
#   python models/rfd3/scripts/report_partial_sweep.py --out <OUT_DIR> \
#     [--discover <LOG_ROOT>] [--drop-incomplete] <sweep dir ...>
# It labels every setting complete / training-only and refuses to invent a
# holdout number for a job that was stopped before its validation pass.
#
# Usage:
#   bash models/rfd3/scripts/run_nmf_zkp_pdb_sweep.sh
#   LAYER_SET=one LAYER=token_initializer.process_pll bash models/rfd3/scripts/run_nmf_zkp_pdb_sweep.sh
#   DATA=... PARQUET=... PDB_MIRROR=... PROJECT_ROOT=/backup01/zzj/protein/foundry LOG_ROOT=... CKPT=... PYTHON=python SEED=42 MAX_EPOCHS=5
#   GPU=2  (default: use idle RTX A6000 GPU 2; set GPU=4 if needed)

set -uo pipefail

# Server project root. Override with PROJECT_ROOT if the checkout is elsewhere.
PROJECT_ROOT="${PROJECT_ROOT:-/backup01/zzj/protein/foundry}"
if [[ ! -d "${PROJECT_ROOT}/models/rfd3/src/rfd3" ]]; then
  # Fallback for running the script from another checkout location.
  PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
fi
REPO_ROOT="${PROJECT_ROOT}"
cd "$REPO_ROOT"
# Training/preflight must import the in-repo rfd3/foundry sources, not the
# stale copies installed into the conda env's site-packages.
export PYTHONPATH="${REPO_ROOT}/src:${REPO_ROOT}/models/rfd3/src:${REPO_ROOT}/models/rfd3na/src${PYTHONPATH:+:${PYTHONPATH}}"

DATA="${DATA:-/dev/shm/pdb_metadata_latest}"
PARQUET="${PARQUET:-/dev/shm/pdb_metadata_latest}"
# CIF/PDB mirror is separate from metadata parquet. The metadata dir only has
# interfaces_df.parquet / pn_units_df.parquet / rfd3_latest.ckpt.
PDB_MIRROR="${PDB_MIRROR:-/dev/shm/pdb_mirror}"
# AtomWorks resolves the chemical component dictionary through this environment variable.
export CCD_MIRROR_PATH="${CCD_MIRROR_PATH:-/dev/shm/ccd_mirror}"
export CCD_PATH="${CCD_PATH:-/dev/shm/ccd_mirror}"
# H-bond featurization (calculate_hbonds > 0) shells out to HBPLUS. Pick the
# first binary that actually exists instead of trusting a hard-coded path: the
# checked-in `.env` points at $HOME/protein, while older notes mention /root.
if [[ -z "${HBPLUS_PATH:-}" ]]; then
  for _hbplus_candidate in \
    "${HOME:-/home/zzj}/protein/HBPLUS/hbplus/hbplus" \
    "/root/protein/HBPLUS/hbplus/hbplus"; do
    if [[ -x "${_hbplus_candidate}" ]]; then
      HBPLUS_PATH="${_hbplus_candidate}"
      break
    fi
  done
  HBPLUS_PATH="${HBPLUS_PATH:-${HOME:-/home/zzj}/protein/HBPLUS/hbplus/hbplus}"
fi
export HBPLUS_PATH
# GPU 2 is currently idle on the supplied machine. Override with GPU=4 if
# another free A6000 is preferred; do not use busy GPUs 0, 1, 3, or 5.
GPU="${GPU:-2}"
export CUDA_VISIBLE_DEVICES="${GPU}"
LOG_ROOT="${LOG_ROOT:-/backup01/zzj/logs/train_nmf_zkp_pdb}"
CKPT="${CKPT:-/dev/shm/pdb_metadata_latest/rfd3_latest.ckpt}"
# Pick an interpreter that can actually import the stack, instead of trusting a
# single hard-coded conda path. PYTHONPATH is already exported above, so a
# candidate only needs pandas + torch installed. Explicit PYTHON always wins.
if [[ -z "${PYTHON+x}" ]]; then
  python_candidates=(
    "${RC_PYTHON:-}"
    "/backup01/zzj/rc-cu128/bin/python"
    "${HOME:-/home/zzj}/anaconda3/envs/rc/bin/python"
    "/opt/conda/envs/rc/bin/python"
    "$(command -v python 2>/dev/null)"
  )
  python_rejected=()
  for _candidate in "${python_candidates[@]}"; do
    [[ -n "${_candidate}" && -x "${_candidate}" ]] || continue
    if "${_candidate}" -c 'import pandas, foundry, rfd3' >/dev/null 2>&1; then
      PYTHON="${_candidate}"
      break
    fi
    python_rejected+=("${_candidate}")
  done
  if [[ -z "${PYTHON:-}" ]]; then
    # Nothing usable found: fall back to the active interpreter so the
    # preflight below prints the real import error for the user to see.
    PYTHON="python"
    echo "WARNING: no candidate interpreter could import pandas/foundry/rfd3." >&2
    echo "         tried: ${python_rejected[*]:-<none>}" >&2
    echo "         falling back to '${PYTHON}' (from PATH: $(command -v python || echo none))." >&2
    echo "         Set PYTHON=/path/to/rc-env/bin/python (or RC_PYTHON=...) to override." >&2
  fi
fi
echo "Using PYTHON=${PYTHON}"

# Validate all external inputs before launching the multi-job sweep. This avoids
# wasting hours when a parquet, checkpoint, PDB mirror, or CCD mirror is missing.
for required_path in \
  "${PARQUET}/interfaces_df.parquet" \
  "${PARQUET}/pn_units_df.parquet" \
  "${CKPT}" \
  "${PDB_MIRROR}" \
  "${CCD_MIRROR_PATH}"; do
  if [[ ! -e "${required_path}" ]]; then
    echo "ERROR: required path does not exist: ${required_path}" >&2
    exit 1
  fi
done

# Fail once, before launching every sweep job, if the runtime environment is
# unusable.  In particular, pandas is imported by foundry's logging module.
if ! "${PYTHON}" - <<'PY'
import pandas
import foundry
import rfd3
print(f"Using Python: {__import__('sys').executable}")
print(f"Using pandas: {pandas.__file__}")
print(f"Using foundry: {foundry.__file__}")
print(f"Using rfd3: {rfd3.__file__}")
PY
then
  echo "ERROR: Python environment failed the pandas/foundry/rfd3 import check." >&2
  echo "  interpreter used: ${PYTHON}" >&2
  echo "  Find the env that has the stack, for example:" >&2
  echo "    for p in /backup01/zzj/rc-cu128/bin/python \"\$HOME/anaconda3/envs/rc/bin/python\"; do" >&2
  echo "      \"\$p\" -c 'import pandas, torch, foundry, rfd3' 2>/dev/null && echo \"OK: \$p\"" >&2
  echo "    done" >&2
  echo "  Then rerun with PYTHON=/that/python (or export RC_PYTHON=/that/python)." >&2
  exit 1
fi

SEED="${SEED:-42}"
MAX_EPOCHS="${MAX_EPOCHS:-580}"
INCLUDE_BASELINE="${INCLUDE_BASELINE:-1}"
INCLUDE_ALL="${INCLUDE_ALL:-0}"
SWEEP_STAMP="${SWEEP_STAMP:-$(date +%Y-%m-%d_%H-%M-%S)}"
SWEEP_DIR="${SWEEP_DIR:-${LOG_ROOT}/sweep_nmf_zkp_pdb_${SWEEP_STAMP}}"
TABLE_OUT="${TABLE_OUT:-${SWEEP_DIR}/comparison_table.md}"
CSV_OUT="${CSV_OUT:-${SWEEP_DIR}/comparison_table.csv}"
mkdir -p "$SWEEP_DIR"

# ---------------------------------------------------------------------------
# GPU sizing. The plain defaults (D=4 diffusion samples, 1920-atom crop, 2
# dataloader workers) were sized for a ~12 GiB card. Pick a preset for the
# card actually in use; explicit env vars always win over the preset:
#   PRESET=a6000    48 GiB A6000, safe first step   (D=16, 1920 atoms, 8 workers)
#   PRESET=a6000xl  48 GiB, larger crop -- PROBE the peak memory before a sweep
#   PRESET=small    ~12 GiB; same as the plain defaults, spelled out
#
# Why these numbers: the dominant activation is the atom-pair tensor, so peak
# VRAM ~ D * L^2 with L = min(crop_size * ~14, max_atoms_in_crop). Relative to
# the old default (D=4, L=1920 -> 14.7M units):
#   D=16, L=1920 -> 59M   (~4x, the a6000 preset)
#   D=16, L=2560 -> 105M  (~7x, the a6000xl preset -- do not start here blind)
# NOTE max_atoms_in_crop is the binding limit: CROP_SIZE=256 needs ~3584 atoms,
# so at MAX_ATOMS=1920 the effective crop is only ~137 residues.
# Validation always uses diffusion_batch_size=1, so a large D can never OOM the
# holdout pass. After a run, read the true peak from
# <sweep_dir>/<tag>.run_summary.json -> cost.gpu_peak_allocated_bytes
# (or watch: nvidia-smi --query-gpu=memory.used --format=csv -l 5).
#
# Wall-clock levers, in order of effect:
#   1. several GPUs at once (see the header recipe), 
#   2. NUM_WORKERS/PREFETCH (atomworks featurisation is CPU heavy; 32 cores),
#   3. DIFFUSION_BS: each loaded structure then yields D noise samples, so the
#      per-structure host cost is amortised. Those samples are correlated, so
#      lowering MAX_EPOCHS by ~2x (not by D) keeps the gradient quality.
# ---------------------------------------------------------------------------
case "${PRESET:-}" in
  ""|default) ;;
  small)
    : "${DIFFUSION_BS:=4}"; : "${CROP_SIZE:=256}"; : "${MAX_ATOMS:=1920}"
    : "${NUM_WORKERS:=2}"; : "${PREFETCH:=2}"
    ;;
  a6000)
    : "${DIFFUSION_BS:=16}"; : "${CROP_SIZE:=256}"; : "${MAX_ATOMS:=1920}"
    : "${NUM_WORKERS:=8}"; : "${PREFETCH:=4}"
    ;;
  a6000xl)
    : "${DIFFUSION_BS:=16}"; : "${CROP_SIZE:=256}"; : "${MAX_ATOMS:=2560}"
    : "${NUM_WORKERS:=8}"; : "${PREFETCH:=4}"
    ;;
  *)
    echo "Unknown PRESET=${PRESET}. Use small, a6000, a6000xl, or leave it unset." >&2
    exit 1
    ;;
esac
echo "PRESET=${PRESET:-default}  DIFFUSION_BS=${DIFFUSION_BS:-4}  CROP_SIZE=${CROP_SIZE:-256}  MAX_ATOMS=${MAX_ATOMS:-1920}  WORKERS=${NUM_WORKERS:-2}"

# 128 examples/epoch gives a less noisy estimate of the training distribution
# while keeping the four-setting sweep tractable. Override with N_EXAMPLES for
# a controlled ablation.
COMMON_OVERRIDES=(
  "paths.data.pdb_data_dir=${PDB_MIRROR}"
  "paths.data.pdb_parquet_dir=${PARQUET}"
  "paths.log_dir=${SWEEP_DIR}"
  "logger=csv"
  "seed=${SEED}"
  "trainer.max_epochs=${MAX_EPOCHS}"
  "save_checkpoints=false"
  "trainer.checkpoint_every_n_epochs=1000000000"
  "datasets.diffusion_batch_size_train=${DIFFUSION_BS:-4}"
  "datasets.crop_size=${CROP_SIZE:-256}"
  "datasets.max_atoms_in_crop=${MAX_ATOMS:-1920}"
  "trainer.n_examples_per_epoch=${N_EXAMPLES:-128}"
  # Disable periodic validation; train_lora.py performs exactly one explicit
  # validation after fit completes.
  "trainer.validate_every_n_epochs=1000000000"
  "dataloader.train.dataloader_params.num_workers=${NUM_WORKERS:-2}"
  "dataloader.train.dataloader_params.prefetch_factor=${PREFETCH:-2}"
)

# Escape hatch for extra hydra overrides applied to every job, e.g. a fast
# evaluation-only smoke test that trains for zero steps and only runs the
# holdout pass:
#   MAX_EPOCHS=1 EXTRA_OVERRIDES="datasets.val.pdb_holdout.max_examples=4" ...
if [[ -n "${EXTRA_OVERRIDES:-}" ]]; then
  # shellcheck disable=SC2206
  COMMON_OVERRIDES+=(${EXTRA_OVERRIDES})
fi

# Opt-in per-phase timing. A replacement-NMF job freezes the entire base model
# (train_lora.py sets requires_grad=False on every parameter, then injects only
# the factors), so it can skip the weight-gradient GEMMs -- but the forward pass
# and the activation-gradient path are identical to the baseline, and the
# dataloader is shared. TimingCallback is the only way to see which of those
# dominates a step: it logs, per step, forward_loss_backward / optimizer_step /
# train_loader_next to metrics.csv as `timings/*` and prints a table every
# TIMING_EVERY steps:
#   TIMING=1 ... bash models/rfd3/scripts/run_nmf_zkp_pdb_sweep.sh
# Read it as: timings/forward_loss_backward is the part that *could* differ
# between a frozen and a fully trainable run; timings/train_loader_next is the
# host-side cost that cannot, and if it is of the same order the sweep is
# dataloader bound and no amount of freezing will speed it up.
if [[ "${TIMING:-0}" == "1" ]]; then
  COMMON_OVERRIDES+=("+callbacks.timing_callback._target_=foundry.callbacks.timing_logging.TimingCallback")
  COMMON_OVERRIDES+=("+callbacks.timing_callback.log_every_n=${TIMING_EVERY:-100}")
fi

LAYER_SET="${LAYER_SET:-encoder}"
LAYER="${LAYER:-}"

layer_jobs_for() {
  local family="$1"
  case "${family}" in
    encoder)
      printf '%s\n' \
        "process_s_init|token_initializer.process_s_init.1" \
        "process_z_init|token_initializer.process_z_init.1" \
        "process_c|diffusion_module.process_c.1" \
        "process_s_trunk|token_initializer.process_s_trunk.1" \
        "transition_post_token_l1|token_initializer.transition_post_token.linear_1" \
        "transition_post_atom_l1|token_initializer.transition_post_atom.linear_1"
      ;;
    proj)
      printf '%s\n' \
        "process_pll|token_initializer.process_pll" \
        "project_pll|token_initializer.project_pll" \
        "process_n_atom|diffusion_module.process_n.0.1" \
        "process_n_token|diffusion_module.process_n.1.1" \
        "process_single_l|token_initializer.process_single_l.1" \
        "process_z|token_initializer.process_z.1"
      ;;
    head)
      printf '%s\n' \
        "to_r_update|diffusion_module.to_r_update.1" \
        "sequence_head|diffusion_module.sequence_head.linear"
      ;;
    *)
      echo "Unknown LAYER_SET family: ${family}" >&2
      return 1
      ;;
  esac
}

JOBS=()
if [[ "${INCLUDE_BASELINE}" == "1" ]]; then
  # NOTE: no NMF/LoRA injection and no parameter_freezing_config is set here, so
  # every RFD3 parameter (~168M) stays trainable. This baseline is therefore a
  # FULL FINE-TUNE of the released checkpoint, not a frozen-pretrained baseline.
  # To evaluate the untouched checkpoint instead, use the zero-step trick
  # (trainer.max_epochs=1 still runs the post-fit holdout pass) or apply
  #   EXTRA_OVERRIDES="+ckpt_config.parameter_freezing_config.freeze_by_default=true"
  # (a fully frozen model yields a loss without grad_fn, so it cannot go through
  # training_step/backward -- that combination only works with zero train steps).
  JOBS+=("baseline|nmf_zkp_pdb|name=baseline +nmf.enabled=false ckpt_config.path=${CKPT} ckpt_config.reset_optimizer=true")
fi

append_layer_jobs() {
  local family="$1"
  local spec tag path
  while IFS= read -r spec; do
    [[ -z "${spec}" ]] && continue
    IFS='|' read -r tag path <<<"${spec}"
    JOBS+=("${tag}|nmf_zkp_single_layer_pdb|name=${tag} nmf.target_keywords=[${path}] nmf.match_mode=exact nmf.max_replacements=1 nmf.apply_to_token_initializer=true")
  done < <(layer_jobs_for "${family}")
}

case "${LAYER_SET}" in
  encoder) append_layer_jobs encoder ;;
  proj) append_layer_jobs proj ;;
  head) append_layer_jobs head ;;
  all)
    append_layer_jobs encoder
    append_layer_jobs proj
    append_layer_jobs head
    ;;
  one)
    if [[ -z "${LAYER}" ]]; then
      echo "LAYER_SET=one requires LAYER=<module.path>, e.g. LAYER=token_initializer.process_pll" >&2
      exit 1
    fi
    tag="$(echo "${LAYER}" | tr './' '__')"
    JOBS+=("${tag}|nmf_zkp_single_layer_pdb|name=${tag} nmf.target_keywords=[${LAYER}] nmf.match_mode=exact nmf.max_replacements=1 nmf.apply_to_token_initializer=true")
    ;;
  *)
    echo "Unknown LAYER_SET=${LAYER_SET}. Use encoder, proj, head, all, or one." >&2
    exit 1
    ;;
esac

run_one() {
  local tag="$1"
  local experiment="$2"
  local extras="$3"
  local run_log="${SWEEP_DIR}/${tag}.run.log"
  echo "============================================================"
  echo "[$(date '+%F %T')] START ${tag}  experiment=${experiment}"
  echo "============================================================"

  local extra_arr=()
  if [[ -n "${extras}" ]]; then
    # shellcheck disable=SC2206
    extra_arr=(${extras})
  fi

  set +e
  ${PYTHON} models/rfd3/src/rfd3/train_lora.py \
    "experiment=${experiment}" \
    "${COMMON_OVERRIDES[@]}" \
    "${extra_arr[@]}" \
    2>&1 | tee "${run_log}"
  local rc=${PIPESTATUS[0]}
  set -e

  # Require every configured job to produce a successful holdout evaluation.
  # A zero exit code without val_metrics is not a valid paper-comparison run.
  local validation_dir="${SWEEP_DIR}/train/${tag}"
  if [[ "${rc}" == "0" ]] && ! find "${validation_dir}" -type f -path '*/val_metrics/validation_output_all_epochs.csv' -print -quit | grep -q .; then
    echo "${tag}: missing validation_output_all_epochs.csv; marking job failed" >&2
    rc=2
  fi
  echo "${rc}" > "${SWEEP_DIR}/${tag}.exit_code"
  echo "[$(date '+%F %T')] END ${tag} exit=${rc}"
  return 0
}

overall_failed=0
for job in "${JOBS[@]}"; do
  IFS='|' read -r tag experiment extras <<<"${job}"
  run_one "${tag}" "${experiment}" "${extras}"
  job_exit="$(cat "${SWEEP_DIR}/${tag}.exit_code")"
  if [[ "${job_exit}" != "0" ]]; then
    overall_failed=1
  fi
done

"${PYTHON}" - <<'PY' "$SWEEP_DIR" "$TABLE_OUT" "$CSV_OUT" "$CKPT"
import csv
import json
import sys
from pathlib import Path

sweep_dir = Path(sys.argv[1])
table_out = Path(sys.argv[2])
csv_out = Path(sys.argv[3])
ckpt = sys.argv[4]

preferred = ["baseline"]
found = [p.name.replace(".exit_code", "") for p in sorted(sweep_dir.glob("*.exit_code"))]
tags = [t for t in preferred if t in found] + [t for t in found if t not in preferred]


def load_summary(tag: str):
    candidates = [sweep_dir / f"{tag}.run_summary.json", *sweep_dir.glob("*.run_summary.json")]
    for p in candidates:
        try:
            data = json.loads(p.read_text())
        except Exception:
            continue
        name = str(data.get("name", ""))
        if p.name.startswith(tag) or tag in name or tag.replace("_", "-") in name:
            data["_summary_path"] = str(p)
            return data
    exit_code = (sweep_dir / f"{tag}.exit_code").read_text().strip() if (sweep_dir / f"{tag}.exit_code").exists() else "?"
    return {
        "status": "failed" if exit_code not in {"0", ""} else "missing",
        "trainable_params": None,
        "total_params": None,
        "best_val_lddt": None,
        "best_val_loss": None,
        "_summary_path": "summary_json_missing",
    }


def fmt(v, digits=4):
    if v is None or v == "":
        return ""
    if isinstance(v, (int, float)):
        return f"{v:.{digits}f}"
    return str(v)


def load_replacements(tag: str) -> str:
    for p in [
        sweep_dir / f"{tag}.nmf_replacements.json",
        sweep_dir / f"nmf-zkp-{tag.replace('zkp_', '')}-pdb.nmf_replacements.json",
        *sweep_dir.glob(f"*{tag}*.nmf_replacements.json"),
    ]:
        if not p.exists():
            continue
        try:
            rep = json.loads(p.read_text())
        except Exception:
            continue
        records = rep.get("records", [])
        if not records:
            return str(p)
        return " ; ".join(
            f"{x.get('module_name')}[{x.get('module_type')}] "
            f"in={x.get('in_features')} out={x.get('out_features')} "
            f"rank={x.get('rank')} params={x.get('nmf_params')}"
            for x in records
        )
    return ""


headers = [
    "setting",
    "status",
    "best_val_lddt",
    "best_val_loss",
    "final_train_loss",
    "best_train_loss",
    "final_train_lddt",
    "best_train_lddt",
    "final_seq_recovery",
    "final_coordinate_mse",
    "trainable_params",
    "total_params",
    "trainable_fraction",
    "proof_family",
    "replaced_layers",
]
family = {
    "baseline": "none",
    "process_s_init": "input-integrity M",
    "process_z_init": "input-integrity M",
    "process_c": "input-integrity M",
    "process_s_trunk": "input-integrity M",
    "transition_post_token_l1": "input-integrity M",
    "transition_post_atom_l1": "input-integrity M",
    "process_pll": "intermediate-state M",
    "project_pll": "intermediate-state M",
    "process_n_atom": "intermediate-state M",
    "process_n_token": "intermediate-state M",
    "process_single_l": "intermediate-state M",
    "process_z": "intermediate-state M",
    "to_r_update": "output-consistency M",
    "sequence_head": "output-consistency M",
}

rows = []
md = [
    "# ZKP-oriented NMF PDB sweep",
    "",
    f"- Baseline checkpoint: `{ckpt}`",
    f"- Sweep dir: `{sweep_dir}`",
    "",
    "## Layer groups",
    "",
    "- Each job replaces **exactly one** Linear via `match_mode=exact` and `max_replacements=1`.",
    "- Encoder defaults: `process_s_init.1`, `process_z_init.1`, `process_c.1`, `process_s_trunk.1`, `transition_post_token.linear_1`, `transition_post_atom.linear_1`.",
    "- Projection defaults: `process_pll`, `project_pll`, `process_n.{0,1}.1`, `process_single_l.1`, `process_z.1`.",
    "- Head defaults: `to_r_update.1`, `sequence_head.linear`.",
    "- excluded: `to_q` / `to_k` / `to_v` / `to_b` / `to_g`, `process_r`, `process_a`",
    "",
    "| " + " | ".join(headers) + " |",
    "| " + " | ".join(["---"] * len(headers)) + " |",
]

for tag in tags:
    s = load_summary(tag)
    exit_code = (sweep_dir / f"{tag}.exit_code").read_text().strip() if (sweep_dir / f"{tag}.exit_code").exists() else ""
    status = s.get("status") or ("success" if exit_code == "0" else f"exit={exit_code}")
    row = {
        "setting": tag,
        "status": status,
        # These remain empty when the sweep intentionally has no validation
        # loader. Never substitute training metrics into validation fields.
        "best_val_lddt": fmt(s.get("best_val_lddt")),
        "best_val_loss": fmt(s.get("best_val_loss")),
        "final_train_loss": fmt(s.get("final_train_loss") or s.get("metrics", {}).get("train/per_epoch_total_loss")),
        "best_train_loss": fmt(s.get("best_epoch_loss")),
        "final_train_lddt": fmt(s.get("final_train_lddt") or s.get("metrics", {}).get("train/per_epoch_mean_lddt_protein")),
        "best_train_lddt": fmt(s.get("best_epoch_lddt")),
        "final_seq_recovery": fmt(s.get("final_train_seq_recovery") or s.get("metrics", {}).get("train/per_epoch_seq_recovery")),
        "final_coordinate_mse": fmt(s.get("final_train_coordinate_mse") or s.get("metrics", {}).get("train/per_epoch_mse_loss_mean")),
        "trainable_params": s.get("trainable_params"),
        "total_params": s.get("total_params"),
        "trainable_fraction": fmt(
            (s.get("trainable_params") / s.get("total_params"))
            if s.get("trainable_params") is not None and s.get("total_params")
            else None
        ),
        "proof_family": family.get(tag, ""),
        "replaced_layers": load_replacements(tag),
    }
    rows.append(row)
    md.append("| " + " | ".join("" if row.get(h) is None else str(row.get(h)) for h in headers) + " |")

md.extend(
    [
        "",
        "## Notes",
        "",
        "- Training uses the PDB dataset, not `single_structure_data`.",
        "- One Linear is replaced per job. Parent Transition / Sequential names are not expanded.",
        "- The middle square `M` of that single layer is the intended ZKP proof target.",
        "- Validation metrics are intentionally blank for this training-only sweep; do not interpret training metrics as generalization metrics.",
        "- The final holdout validation runs once after training; periodic validation is disabled.",
        "- The generated paper_summary.csv/.md report per-example lDDT mean, SD, median, bootstrap 95% CI, paired baseline deltas, and coverage.",
        "",
    ]
)

table_out.write_text("\n".join(md) + "\n")
with csv_out.open("w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=headers)
    w.writeheader()
    w.writerows(rows)
print("\n".join(md))
print(f"\nWrote: {table_out}")
print(f"Wrote: {csv_out}")
PY

# Build paper-level statistics from the per-example holdout CSVs. This is
# intentionally run after all jobs, and never substitutes training metrics for
# validation metrics.
if ! "${PYTHON}" models/rfd3/scripts/summarize_nmf_zkp_pdb_sweep.py "${SWEEP_DIR}" --seed "${SEED}"; then
  echo "Paper summary generation failed; validation CSVs may be missing lDDT." >&2
  overall_failed=1
fi

"${PYTHON}" models/rfd3/scripts/plot_nmf_zkp_pdb_metrics.py "${SWEEP_DIR}" --ckpt "${CKPT}" || true

# Cost/resource table (wall time, peak GPU memory, trainable fraction per
# setting). The banner below has always advertised these files, but nothing
# produced them; run the summariser that actually writes them.
if ! "${PYTHON}" models/rfd3/scripts/summarize_nmf_zkp_cost.py "${SWEEP_DIR}"; then
  echo "Training cost summary generation failed (pandas missing?)." >&2
  overall_failed=1
fi

echo ""
echo "Done. Comparison table:"
echo "  ${TABLE_OUT}"
echo "  ${CSV_OUT}"
echo "Paper figures (if metrics.csv exists):"
echo "  ${SWEEP_DIR}/figures/paper_training_curves.pdf"
echo "  ${SWEEP_DIR}/paper_metrics.md"
echo "Paper full-metric evaluation:"
echo "  ${SWEEP_DIR}/paper_summary.csv"
echo "  ${SWEEP_DIR}/paper_paired_deltas.csv"
echo "  ${SWEEP_DIR}/paper_per_example_lddt.csv"

echo "Training cost summary:"
echo "  ${SWEEP_DIR}/paper_training_cost.csv"
echo "  ${SWEEP_DIR}/paper_training_cost.md"

if [[ "${overall_failed}" != "0" ]]; then
  echo "Sweep finished with one or more failed jobs; see *.run.log and *.exit_code." >&2
  exit 1
fi
